name: Build Artifacts

permissions:
  contents: write

on:
  push:
    branches:
      - '*'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout battlebitapirunner-modules code
      uses: actions/checkout@v4
      with:
        repository: 'Bluscream/battlebitapirunner-modules'
        fetch-depth: 0

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Checkout BattleBitAPIRunner code
      uses: actions/checkout@v4
      with:
        repository: 'BattleBit-Community-Servers/BattleBitAPIRunner'
        path: 'BattleBitAPIRunner'
        fetch-depth: 0

    - name: NuGet Restore
      run: dotnet restore BattleBitAPIRunner/BattleBitAPIRunner.csproj

    - name: Build and Publish BattleBitAPIRunner project
      run: dotnet publish BattleBitAPIRunner/BattleBitAPIRunner.csproj -c Release -o ./publish --self-contained false --framework net6.0 --runtime win-x64

    - name: Build nuget
      run: dotnet build BattleBitAPIRunner/BattleBitAPIRunner.csproj -c Release

    - name: Create NuGet package
      run: dotnet pack BBRAPIModules/BBRAPIModules.csproj --configuration Release --output ./nuget

    - name: Upload NuGet package artifact
      uses: actions/upload-artifact@v3
      with:
        name: NuGet Package
        path: ./nuget/*.nupkg

    - name: Upload Release artifact
      uses: actions/upload-artifact@v3
      with:
        name: BattleBitAPIRunner-beta
        path: ./publish/*

    - name: Build battlebitapirunner-modules
      run: dotnet build .
